logging:
    file:
        name: sboard.log
        path: /logs
    level:
        org:
            hibernate:
                type:
                    descriptor:
                        sql: trace
        root: info
mybatis:
    mapper-locations: classpath:mappers/**/*.xml
server:
    port: 8080
    servlet:
        context-path: /
spring:
    mail:
        host: smtp.gmail.com
        port: 587
        username: wnstj050505@gmail.com
        password: tbph cken peoy jlqt
        properties:
          mail:
              smtp:
                  auth: true
                  timeout: 5000
                  starttls:
                      enable: true
    application:
        name: sboard
        version: '@version@'
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: Qwert123@
        url: jdbc:mysql://3.34.124.218:3306/board
        username: board
    devtools:
        livereload:
            enabled: true
    jpa:
        database: mysql
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                format_sql: true
                show_sql: true
    thymeleaf:
        prefix: classpath:/templates
